# Pandas compatible data sources
- text, - csv, josn, html tables etc
- binary - for io performance or other software like excel
- relational dbs (all major dbs)

----
### Tate Collection

In [9]:
import pandas as pd
import os

In [2]:
path = os.path.join('.', 'data', 'artwork_data.csv')
df = pd.read_csv(path, nrows=5)
df

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
2,1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785.0,1922,support: 343 x 467 mm,343,467,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
3,1038,A00004,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922,support: 318 x 394 mm,318,394,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...
4,1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919,image: 243 x 335 mm,243,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...

In [3]:
# Pandas assigns incremental indices to the data frame, but we already have an id column...
df = pd.read_csv(path, index_col='id', nrows=5)
df

,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
id,,,,,,,,,,,,,,,,,,,
1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785.0,1922,support: 343 x 467 mm,343,467,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
1038,A00004,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922,support: 318 x 394 mm,318,394,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...
1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919,image: 243 x 335 mm,243,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...

In [5]:
# for our needs, we only need the artist column...
df = pd.read_csv(path, index_col='id', usecols=['id', 'artist'], nrows=5)
# we could also pass column indices 0 and 2 or the names
df

              artist
id
1035   Blake, Robert
1036   Blake, Robert
1037   Blake, Robert
1038   Blake, Robert
1039  Blake, William

In [7]:
# Good to define columns in constant cariable
COLS_TO_USE = ['id', 'artist', 'title', 'medium', 'year', 'acquisitionYear', 'height', 'width', 'units']
df = pd.read_csv(path, index_col='id', usecols=COLS_TO_USE)
df.head()

/usr/local/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (9,13) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,artist,title,medium,year,acquisitionYear,width,height,units
id,,,,,,,,
1035,"Blake, Robert",A Figure Bowing before a Seated Old Man with h...,"Watercolour, ink, chalk and graphite on paper....",NaN,1922.0,394,419,mm
1036,"Blake, Robert","Two Drawings of Frightened Figures, Probably f...",Graphite on paper,NaN,1922.0,311,213,mm
1037,"Blake, Robert",The Preaching of Warning. Verso: An Old Man En...,Graphite on paper. Verso: graphite on paper,1785,1922.0,343,467,mm
1038,"Blake, Robert",Six Drawings of Figures with Outstretched Arms,Graphite on paper,NaN,1922.0,318,394,mm
1039,"Blake, William",The Circle of the Lustful: Francesca da Rimini...,Line engraving on paper,1826,1919.0,243,335,mm

In [8]:
# We have a warning, pandas cannot predict data type. We can deal with this later

# As this is the data we want to use for forthcoming work, we should save this subset

# The pickle format is python-native format, we will only be using this with python code.

df.to_pickle(os.path.join('.','data_frame.pickle'))

----
## Artists 

Artist data is found in different json files, with similar schema. This is not the ideal format for querying, so we'll need to convert it first. Best to use the method family:

```
    pd.DataFrame.from_*()  
```

In [13]:
# Example use of from_records
records = [('Espresso', '5$'), ('Falt White', '10$')]
pd.DataFrame.from_records(records, columns=['Coffee', 'Price'])

       Coffee Price
0    Espresso    5$
1  Falt White   10$

Read the artist json files...

In [11]:
KEYS_TO_USE = ['id', 'all_artists', 'title', 'medium', 'dateText', 'acquisitionYear', 'height', 'width', 'units']

In [17]:
import json 
def get_record_from_file(file_path , keys_to_use):
    """ Process single json file and return a 
    tuple containing specific fields."""
    
    with open(file_path) as artwork_file:
        content = json.load(artwork_file)

    record = []
    for field in keys_to_use:
        record.append(content[field])
        
    return tuple(record)

In [20]:
# Use get_record_from_file to process the first files
import os

SAMPLE_JSON = os.path.join('.', 'data','artworks','a','000','a00001-1035.json')
sample_record = get_record_from_file(SAMPLE_JSON, KEYS_TO_USE)
sample_record

(1035,
 'Robert Blake',
 'A Figure Bowing before a Seated Old Man with his Arm Outstretched in Benediction. Verso: Indecipherable Sketch',
 'Watercolour, ink, chalk and graphite on paper. Verso: graphite on paper',
 'date not known',
 1922,
 '419',
 '394',
 'mm')

Iterate over multiple files...

In [26]:
import os

def read_artworks_from_json(keys_to_use):
    """ Traverse the directories with JSON files.
    For first file in each directory call function
    for processing single file and go to the next
    directory.
    """
    JSON_ROOT = os.path.join('.', 'data','artworks')
    artworks = []
    for root, _, files in os.walk(JSON_ROOT):
        for f in files:
            if f.endswith('json'):
                record = get_record_from_file( os.path.join(root,f), keys_to_use)
                artworks.append(record)
            break # only do first file
    df = pd.DataFrame.from_records(artworks, columns=keys_to_use, index="id") 
    
    return df

In [28]:
df = read_artworks_from_json(KEYS_TO_USE)
df.head()

,all_artists,title,medium,dateText,acquisitionYear,height,width,units
id,,,,,,,,
6620,William Hogarth,A Scene from ‘The Beggar’s Opera’ VI,Oil paint on canvas,1731,1909,762,572,mm
10413,William James Müller,"Study of Pines, Rheinwald",Watercolour on paper,1834,1908,410,269,mm
496,Sir Lawrence Alma-Tadema,A Silent Greeting,Oil paint on wood,1889,1894,229,305,mm
15803,Frederick Walker,The Vagrants,Oil paint on canvas,1868,1886,1264,832,mm
1810,"Sir Edward Coley Burne-Jones, Bt",Head and Hand,Graphite on paper,date not known,1932,165,225,mm